-- Solve 2024-12-30

SELECT H.HISTORY_ID,
    (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * C.DAILY_FEE * (100 - IFNULL(P.DISCOUNT_RATE, 0)) DIV 100 AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
LEFT JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
AND P.DURATION_TYPE = (
    CASE
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE NULL
    END
)
WHERE C.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC;
