-- Solve 2024-12-26

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S
WHERE S.NAME IN ('Python', 'C#')
AND TRUNCATE(D.SKILL_CODE / S.CODE, 0) % 2 = 1
ORDER BY D.ID ASC;
