-- Solve 2024-12-30

SELECT MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01'
    AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
)
AND START_DATE >= '2022-08-01'
AND START_DATE < '2022-11-01'
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY 1 ASC, 2 DESC;
