-- Solve 2024-12-31

SELECT C.CAR_ID,
    C.CAR_TYPE,
    (C.DAILY_FEE * 30 * (100 - IFNULL(P.DISCOUNT_RATE, 0)) DIV 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE (P.DURATION_TYPE = '30일 이상' OR P.DURATION_TYPE IS NULL)
AND C.CAR_TYPE IN ('세단', 'SUV')
AND NOT EXISTS (
    SELECT H.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE H.CAR_ID = C.CAR_ID
    AND H.START_DATE <= '2022-11-30'
    AND '2022-11-01' <= H.END_DATE
)
HAVING FEE >= 500000
AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
