-- Solve 2025-01-02

WITH FE AS (
    SELECT BIT_OR(CODE) AS CODES -- BIT_OR 대신 SUM을 사용해도 된다.
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT
    CASE
        WHEN D.SKILL_CODE & FE.CODES != 0
        AND D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') != 0
        THEN 'A'
        WHEN D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') != 0
        THEN 'B'
        WHEN D.SKILL_CODE & FE.CODES != 0
        THEN 'C'
        ELSE NULL
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM DEVELOPERS D, FE
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, D.ID ASC;
