-- Solve 2024-12-30

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE T
JOIN ITEM_INFO I
ON T.ITEM_ID = I.ITEM_ID
JOIN ITEM_INFO P
ON T.PARENT_ITEM_ID = P.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY 1 DESC;
